"""
Django settings for UWAreservation project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-3iedd=_*e1jqy6^bz_+5-5aaxi&&so8zj0d^zu00p-mr+&2)rz'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 'anymail',  # Email service - disabled for testing
    'tours',
    'accounts',
    'booking',
    # 'communications',  # Disabled for testing
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'UWAreservation.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'accounts.context_processors.notifications',
            ],
        },
    },
]

WSGI_APPLICATION = 'UWAreservation.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Email Configuration using django-anymail
# Temporarily disabled for testing core functionality
# from decouple import config

# Email backend configuration
# EMAIL_BACKEND = "anymail.backends.mailgun.EmailBackend"  # Example with Mailgun
# EMAIL_BACKEND = "anymail.backends.sendgrid.EmailBackend"  # Alternative: SendGrid
EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"  # For development

# Anymail settings (configure based on your email service)
# ANYMAIL = {
#     "MAILGUN_API_KEY": config('MAILGUN_API_KEY', default='your-mailgun-api-key'),
#     "MAILGUN_SENDER_DOMAIN": config('MAILGUN_DOMAIN', default='your-domain.com'),
# }

# Default email settings
DEFAULT_FROM_EMAIL = 'noreply@uwa-tours.com'  # config('DEFAULT_FROM_EMAIL', default='noreply@uwa-tours.com')
EMAIL_SUBJECT_PREFIX = '[UWA Tours] '

# SMS Configuration using Twilio
# TWILIO_ACCOUNT_SID = config('TWILIO_ACCOUNT_SID', default='your-twilio-sid')
# TWILIO_AUTH_TOKEN = config('TWILIO_AUTH_TOKEN', default='your-twilio-token')
# TWILIO_PHONE_NUMBER = config('TWILIO_PHONE_NUMBER', default='+1234567890')

# Celery Configuration for background tasks - disabled for testing
# CELERY_BROKER_URL = config('CELERY_BROKER_URL', default='redis://localhost:6379/0')
# CELERY_RESULT_BACKEND = config('CELERY_RESULT_BACKEND', default='redis://localhost:6379/0')
# CELERY_ACCEPT_CONTENT = ['json']
# CELERY_TASK_SERIALIZER = 'json'
# CELERY_RESULT_SERIALIZER = 'json'
# CELERY_TIMEZONE = TIME_ZONE

# Communication settings - disabled for testing
# SEND_NOTIFICATIONS = config('SEND_NOTIFICATIONS', default=True, cast=bool)
# NOTIFICATION_FROM_EMAIL = config('NOTIFICATION_FROM_EMAIL', default=DEFAULT_FROM_EMAIL)
# NOTIFICATION_FROM_PHONE = config('NOTIFICATION_FROM_PHONE', default=TWILIO_PHONE_NUMBER)

# Authentication settings
LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'
