# Generated by Django 5.0.1 on 2025-08-04 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_options_remove_profile_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('tourist', 'Tourist'), ('guide', 'Tour Guide'), ('operator', 'Tour Operator'), ('staff', 'UWA Staff')], max_length=20, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of this role')),
                ('permissions', models.JSONField(blank=True, default=dict, help_text='Role-specific permissions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='profile',
            name='role',
        ),
        migrations.AddField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='date_joined_tourism',
            field=models.DateField(blank=True, help_text='Date when user started in tourism industry', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='guide_experience_years',
            field=models.PositiveIntegerField(blank=True, help_text='Years of experience as a tour guide', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='guide_languages',
            field=models.CharField(blank=True, help_text='Languages spoken by the guide (comma-separated)', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='guide_specializations',
            field=models.CharField(blank=True, help_text='Guide specializations (e.g., wildlife, birding, cultural)', max_length=300),
        ),
        migrations.AddField(
            model_name='profile',
            name='operator_company_name',
            field=models.CharField(blank=True, help_text='Tour operator company name', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='operator_license_number',
            field=models.CharField(blank=True, help_text='Tour operator license number', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='operator_website',
            field=models.URLField(blank=True, help_text='Tour operator website'),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='staff_department',
            field=models.CharField(blank=True, help_text='UWA department', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='staff_employee_id',
            field=models.CharField(blank=True, help_text='UWA staff employee ID', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='staff_position',
            field=models.CharField(blank=True, help_text='Job position/title', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, help_text='A short bio for the user.'),
        ),
        migrations.AddField(
            model_name='profile',
            name='roles',
            field=models.ManyToManyField(blank=True, help_text='User can have multiple roles', to='accounts.userrole'),
        ),
    ]
