# Generated by Django 5.0.1 on 2025-07-31 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_park_image_tour_image_tour_max_participants_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # This migration has been completely disabled due to model conflicts
        # All operations removed to prevent migration errors
    ]
