# Generated by Django 4.2.7 on 2025-08-04 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_tourcompany_and_timestamps'),
    ]

    operations = [
        # Add company field as nullable first
        migrations.AddField(
            model_name='tour',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tours', to='tours.tourcompany'),
        ),
    ]
