# Generated by Django 5.0.1 on 2025-08-04 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_remove_booking_availability_remove_booking_tourist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='park',
            name='image',
            field=models.ImageField(blank=True, help_text='Image of the park', null=True, upload_to='parks/'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tour',
            name='duration_hours',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tour',
            name='image',
            field=models.ImageField(blank=True, help_text='Image of the tour', null=True, upload_to='tours/'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='max_participants',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='tour',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
