# Generated by Django 4.2.7 on 2025-08-04 12:45

from django.db import migrations
import django.db.models.deletion


def create_default_company(apps, schema_editor):
    """Create default UWA company and link all existing tours to it"""
    TourCompany = apps.get_model('tours', 'TourCompany')
    Tour = apps.get_model('tours', 'Tour')
    
    # Create the UWA company
    uwa_company = TourCompany.objects.create(
        name="Uganda Wildlife Authority",
        is_uwa=True,
        description="Official tours offered by the Uganda Wildlife Authority",
        website="https://ugandawildlife.org",
        contact_email="info@ugandawildlife.org",
    )
    
    # Link all existing tours to the UWA company
    Tour.objects.all().update(company=uwa_company)


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_tourcompany_tour_created_at_tour_created_by_and_more'),
    ]

    operations = [
        # First run the Python function to create company and link tours
        migrations.RunPython(create_default_company),
    ]
