# Generated by Django 4.2.7 on 2025-08-04 13:05

from django.db import migrations


def create_uwa_company(apps, schema_editor):
    """Create UWA company and link all existing tours to it"""
    TourCompany = apps.get_model('tours', 'TourCompany')
    Tour = apps.get_model('tours', 'Tour')
    
    # Create the UWA company
    uwa_company = TourCompany.objects.create(
        name="Uganda Wildlife Authority",
        is_uwa=True,
        description="Official tours offered by the Uganda Wildlife Authority",
        website="https://ugandawildlife.org",
        contact_email="info@ugandawildlife.org",
    )
    
    # Link all existing tours to the UWA company
    for tour in Tour.objects.all():
        tour.company = uwa_company
        tour.save()


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_tour_company'),
    ]

    operations = [
        migrations.RunPython(create_uwa_company),
    ]
