# Generated by Django 4.2.7 on 2025-08-04 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_create_uwa_company_and_link_tours'),
    ]

    operations = [
        # Now make the company field required (not null)
        migrations.AlterField(
            model_name='tour',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tours', to='tours.tourcompany'),
        ),
    ]
