# Generated by Django 4.2.7 on 2025-08-04 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0005_create_uwa_company'),
    ]

    operations = [
        # Now make the company field required
        migrations.AlterField(
            model_name='tour',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tours', to='tours.tourcompany'),
        ),
    ]
