# Generated by Django 5.0.1 on 2025-08-04 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_tourcompany_tour_created_at_tour_created_by_and_more'),
        ('tours', '0005_auto_20250804_1327'),
    ]

    operations = [
    ]
