# Generated by Django 5.0.1 on 2025-08-04 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0006_alter_tour_company_not_null'),
        ('tours', '0006_merge_20250804_2126'),
    ]

    operations = [
    ]
