# Generated by Django 5.0.1 on 2025-08-04 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0005_alter_tour_company_not_null'),
        ('tours', '0007_merge_20250804_2143'),
    ]

    operations = [
    ]
