# Generated by Django 5.0.1 on 2025-08-05 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0008_merge_20250804_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='park',
            name='altitude_m',
            field=models.IntegerField(blank=True, help_text='Altitude in meters above sea level', null=True),
        ),
        migrations.AddField(
            model_name='park',
            name='area_sqkm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Area in square kilometers', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='park',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='Contact email for the park', max_length=254),
        ),
        migrations.AddField(
            model_name='park',
            name='contact_phone',
            field=models.CharField(blank=True, help_text='Contact phone number', max_length=20),
        ),
        migrations.AddField(
            model_name='park',
            name='date_established',
            field=models.DateField(blank=True, help_text='Date when the park was established', null=True),
        ),
        migrations.AddField(
            model_name='park',
            name='key_features',
            field=models.TextField(blank=True, help_text='Key physical features and attractions'),
        ),
        migrations.AddField(
            model_name='park',
            name='key_wildlife',
            field=models.TextField(blank=True, help_text='Key wildlife species found in the park'),
        ),
        migrations.AddField(
            model_name='park',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude coordinates', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='park',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude coordinates', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='park',
            name='park_type',
            field=models.CharField(choices=[('national_park', 'National Park'), ('wildlife_reserve', 'Wildlife Reserve'), ('sanctuary', 'Wildlife Sanctuary'), ('forest_reserve', 'Forest Reserve')], default='national_park', max_length=50),
        ),
        migrations.AddField(
            model_name='park',
            name='vegetation_type',
            field=models.TextField(blank=True, help_text='Description of vegetation types'),
        ),
        migrations.AddField(
            model_name='park',
            name='website_url',
            field=models.URLField(blank=True, help_text='Official website URL'),
        ),
    ]
